### ISSUE TITLE
Bug: touchend button with monotouchable option would lock all buttons if touchend event is not triggered

### ISSUE THREAD

**Issue by veloce** [peutetre/mobile-button#24]
Ex on iOS here:
https://github.com/veloce/lichobile/blob/1.1.x/screens/android/playing.png

As of button is right in the bottom of the viewport. When swiping up the iOS context menu with wifi, etc. touchstart will be triggered, locking all buttons but no touchend is never fired. So all other touchend buttons are locked and there is no way to unlock them.

For now I can't use monotouchable at all because of this issue in iOS.

**Comment by veloce** [comment]
I suppose touchcancel could take care of it, but I'm not sure it's predictible in all situations.

**Comment by peutetre** [comment]
Are you talking about the default touch cancel buttons?
